const test = () => {
  return (
    <ul>
      <li><a href="/wiki/Axolotl" title="Axolotl"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-80px -592px"></span><span class="sprite-text">Axolotl</span></span></a></li>
      <li><a href="/wiki/Bee" title="Bee"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-32px -384px"></span><span class="sprite-text">Bee</span></span></a></li>
      <li><a href="/wiki/Cat" title="Cat"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-96px -448px"></span><span class="sprite-text">Cat</span></span></a></li>
      <li><a href="/wiki/Chicken" title="Chicken"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-32px -432px"></span><span class="sprite-text">Chicken</span></span></a></li>
      <li><a href="/wiki/Cow" title="Cow"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-48px -432px"></span><span class="sprite-text">Cow</span></span></a></li>
      <li><a href="/wiki/Donkey" title="Donkey"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-160px -464px"></span><span class="sprite-text">Donkey</span></span></a></li>
      <li><a href="/wiki/Fox" title="Fox"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-48px -368px"></span><span class="sprite-text">Fox</span></span></a></li>
      <li><a href="/wiki/Goat" title="Goat"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-96px -592px"></span><span class="sprite-text">Goat</span></span></a></li>
      <li><a href="/wiki/Hoglin" title="Hoglin"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-0px -400px"></span><span class="sprite-text">Hoglin</span></span></a></li>
      <li><a href="/wiki/Horse" title="Horse"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-144px -464px"></span><span class="sprite-text">Horse</span></span></a></li>
      <li><a href="/wiki/Llama" title="Llama"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-64px -480px"></span><span class="sprite-text">Llama</span></span></a></li>
      <li><a href="/wiki/Mooshroom" title="Mooshroom"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-128px -432px"></span><span class="sprite-text">Mooshroom</span></span></a></li>
      <li><a href="/wiki/Mule" title="Mule"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-80px -480px"></span><span class="sprite-text">Mule</span></span></a></li>
      <li><a href="/wiki/Ocelot" title="Ocelot"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-128px -448px"></span><span class="sprite-text">Ocelot</span></span></a></li>
      <li><a href="/wiki/Panda" title="Panda"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-48px -176px"></span><span class="sprite-text">Panda</span></span></a></li>
      <li><a href="/wiki/Pig" title="Pig"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-96px -432px"></span><span class="sprite-text">Pig</span></span></a></li>
      <li><a href="/wiki/Rabbit" title="Rabbit"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-48px -480px"></span><span class="sprite-text">Rabbit</span></span></a></li>
      <li><a href="/wiki/Sheep" title="Sheep"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-144px -432px"></span><span class="sprite-text">Sheep</span></span></a></li>
      <li><a href="/wiki/Strider" title="Strider"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-48px -512px"></span><span class="sprite-text">Strider</span></span></a></li>
      <li><a href="/wiki/Turtle" title="Turtle"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-32px -160px"></span><span class="sprite-text">Turtle</span></span></a></li>
      <li><a href="/wiki/Wolf" title="Wolf"><span class="nowrap"><span class="sprite entity-sprite" style="background-image:url(https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/40/EntityCSS.png/revision/latest?cb=20211219145540&amp;format=original&amp;format=original);background-position:-16px -448px"></span><span class="sprite-text">Wolf</span></span></a></li>
    </ul>
  );
}

export default test;